- name: README the RSS
  # You may pin to the exact commit or the version.
  # uses: kohrongying/readme-the-rss@d8c38862ef25bb27e3b1062c855d69aa7c474cc3
  uses: kohrongying/readme-the-rss@v1
  with:
    # The URL of the RSS feed
    feed_url: https://ramonh.dev/feed.xml
    # Number of posts to display
    count: 5 # optional, default is 5
    # Path to the readme file
    readme_path: README.md # optional, default is README.md
